### PR TITLE
Universal case modifier RFC

### PR DESCRIPTION
**Pull request by nblumhardt**
[Rendered](https://github.com/nblumhardt/seq-tickets/blob/ci-modifier-rfc/rfcs/0919-ci-modifier.md)

### CODE REVIEW

**Comment by c0shea** [comment]
I like the idea of the `ci` modifier. Am I understanding it correctly that it modifies the closest supported operator or function?

It does seem a little weird that `group by Application ci`  would modify the `group by`, while `group by Application = 'x' ci` would modify the `=` operator. Maybe it's because I'm not used to seeing that. Is there a way to tell it in the later example to apply to the `group by`?

In the `group by Substring(A, 0, 3) ci` example, does the `ci` have no effect since it's not supported on `Substring`, throw an error, or does it fall up the chain to the next closest operator?

**Comment by nblumhardt** [comment]
Thanks for taking a look, @c0shea!

> Am I understanding it correctly that it modifies the closest supported operator or function?

Essentially 👍

> Is there a way to tell it in the later example to apply to the group by?

Yes, that would be `group by (Application = 'x') ci`.

It _is_ a little awkward that introducing a new case-modifiable operation effectively requires a grammar update; might ponder on that point some more......

`Substring(A, 0, 3)` returns a string; `group by <some string> ci` will then perform a case-insensitive grouping with that substring as key.

**Comment by c0shea** [comment]
@nblumhardt Thanks for clarifying how it works.

**Comment by nblumhardt** [comment]
I've updated the RFC to reflect some changes in thinking around how `ci` should bind; the RFC now proposes that `ci` can be applied to _any_ comparison or function call, meaning the grammar is more uniform, but the edge cases have changed slightly.

Also notes that `distinct(x) ci` and `ElementAt(@Properties, 'x')` are both now in-scope.

**Pull request merged**
